
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-keycloak-svc
  namespace: {{ .Values.general.namespace}}
spec:
  selector:
    app: {{ .Release.Name }}-keycloak
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP  

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-keycloak
  namespace: {{ .Values.general.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-keycloak
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-keycloak
    spec:
      containers:
      - name: {{ .Release.Name }}-keycloak
        image: quay.io/keycloak/keycloak:latest
        args: ["start","--optimized"]
        ports:
          - containerPort: 8080
        resources:
          limits:
            memory: 2Gi
          requests:
            memory: 1Gi
        env:
          - name: KC_DB
            value: {{ .Values.postgresql.postgresDatabase }}
          - name: KC_DB_URL
            value: {{ .Values.keycloak.url }}
          - name: KC_DB_USERNAME
            value: {{ .Values.postgresql.postgresUser}}
          - name: KC_DB_PASSWORD
            value: {{ .Values.postgresql.postgresPassword }}
          - name: KC_PROXY
            value: {{ .Values.keycloak.proxy}}
          - name: KC_HOSTNAME_STRICT
            value: {{ .Values.keycloak.strict}}
          - name: KEYCLOAK_ADMIN
            value: {{ .Values.keycloak.user }}
          - name: KEYCLOAK_ADMIN_PASSWORD
            value: {{ .Values.keycloak.password }}
